Repository beour-team/beour-be, pull requests merged in 2025-06, with the labels that each got.

#34 [BE] 최근 등록된 공간을 조회한다.
  src/main/java/com/beour/global/entity/BaseTimeEntity.java
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/main/java/com/beour/space/domain/repository/SpaceRepository.java
  src/main/java/com/beour/space/guest/controller/GuestSpaceController.java
  src/main/java/com/beour/space/guest/dto/RecentCreatedSpcaceListResponseDto.java
  src/main/java/com/beour/space/guest/service/GuestSpaceService.java
  src/main/java/com/beour/wishlist/repository/LikeRepository.java
Labels: 💡 기능, 📚코드 리뷰

#42 [BE] 새로 등록된 공간 조회 responseBody 리팩터링
  src/main/java/com/beour/space/guest/dto/RecentCreatedSpcaceListResponseDto.java
  src/main/java/com/beour/space/guest/service/GuestSpaceService.java
Labels: ♻️ 리팩터링

#39 [BE]지난 예약 조회 API 리팩터링
  src/main/java/com/beour/reservation/commons/entity/Reservation.java
  src/main/java/com/beour/reservation/guest/controller/ReservationGuestController.java
  src/main/java/com/beour/reservation/guest/dto/ReservationListResponseDto.java
  src/main/java/com/beour/reservation/guest/service/ReservationGuestService.java
  src/main/java/com/beour/review/domain/entity/Review.java
  src/main/java/com/beour/review/domain/repository/ReviewRepository.java
  src/main/java/com/beour/user/repository/UserRepository.java
Labels: ♻️ 리팩터링

#45 [BE] 게스트의 찜 관련 기능들을 리팩터링한다.
  src/main/java/com/beour/wishlist/repository/LikeRepository.java
  src/main/java/com/beour/wishlist/service/WishlistService.java
Labels: ♻️ 리팩터링

#44 [BE] 게스트의 예약 관련 기능들을 리팩터링한다.
  src/main/java/com/beour/global/exception/ReservationExceptionHandler.java
  src/main/java/com/beour/reservation/commons/exceptionType/MissMatch.java
  src/main/java/com/beour/reservation/commons/repository/ReservationRepository.java
  src/main/java/com/beour/reservation/guest/controller/ReservationGuestController.java
  src/main/java/com/beour/reservation/guest/dto/ReservationListResponseDto.java
  src/main/java/com/beour/reservation/guest/service/CheckAvailableTimeService.java
  src/main/java/com/beour/reservation/guest/service/ReservationGuestService.java
Labels: ♻️ 리팩터링

#51 [BE] 로그인과 관련된 코드들 어노테이션 수정
  src/main/java/com/beour/token/entity/RefreshToken.java
  src/main/java/com/beour/user/dto/ChangePasswordRequestDto.java
  src/main/java/com/beour/user/dto/ReissueAccesstokenResponseDto.java
  src/main/java/com/beour/user/dto/SignupRequestDto.java
  src/main/java/com/beour/user/service/MyInformationService.java
Labels: ♻️ 리팩터링, 📚코드 리뷰

#53 [BE] SignupRequestDto를 수정한다.
  src/main/java/com/beour/user/dto/SignupRequestDto.java
  src/main/java/com/beour/user/service/SignupService.java
Labels: ♻️ 리팩터링

#54 [BE] GuestSpaceService 필요없는 코드 제거
  src/main/java/com/beour/space/guest/service/GuestSpaceService.java
Labels: ♻️ 리팩터링

#55 [BE] 로그인 관련 기능들을 리팩터링한다.
  src/main/java/com/beour/global/validator/annotation/ValidPhoneNum.java
  src/main/java/com/beour/global/validator/implement/PhoneNumValidator.java
  src/main/java/com/beour/user/controller/LoginController.java
  src/main/java/com/beour/user/dto/FindLoginIdRequestDto.java
  src/main/java/com/beour/user/dto/ResetPasswordRequestDto.java
  src/main/java/com/beour/user/dto/SignupRequestDto.java
  src/main/java/com/beour/user/repository/UserRepository.java
  src/main/java/com/beour/user/service/LoginService.java
Labels: ♻️ 리팩터링

#58 [BE] LoginController @Valid 테스트 코드를 작성한다.
  .gitignore
  src/main/java/com/beour/space/guest/service/GuestSpaceService.java
  src/main/java/com/beour/user/dto/FindLoginIdRequestDto.java
  src/main/java/com/beour/user/dto/ResetPasswordRequestDto.java
  src/test/java/com/beour/user/controller/LoginControllerTest.java
  src/test/java/com/beour/user/controller/LoginControllerValidationTest.java
  sue
Labels: 🧪 테스트

#57 [BE] LoginService 테스트 코드를 구현한다.
  src/main/java/com/beour/user/dto/FindLoginIdRequestDto.java
  src/main/java/com/beour/user/dto/ResetPasswordRequestDto.java
  src/main/java/com/beour/user/repository/UserRepository.java
  src/main/java/com/beour/user/service/LoginService.java
  src/test/java/com/beour/user/service/LoginServiceTest.java
Labels: 🧪 테스트, ♻️ 리팩터링

#59 [BE] 로그인 및 회원가입 API 오류를 고친다.
  src/main/java/com/beour/user/dto/ChangePasswordRequestDto.java
  src/main/java/com/beour/user/dto/FindLoginIdRequestDto.java
  src/main/java/com/beour/user/dto/ResetPasswordRequestDto.java
  src/main/java/com/beour/user/dto/SignupRequestDto.java
Labels: 🥵 핫픽스

#62 [BE] 사용자 정보 RU에 관한 테스트 코드를 작성한다.
  src/main/java/com/beour/user/dto/ChangePasswordRequestDto.java
  src/main/java/com/beour/user/dto/UpdateUserInfoRequestDto.java
  src/main/java/com/beour/user/dto/UserInformationDetailResponseDto.java
  src/main/java/com/beour/user/dto/UserInformationSimpleResponseDto.java
  src/main/java/com/beour/user/service/MyInformationService.java
  src/test/java/com/beour/user/service/MyInformationServiceTest.java
Labels: 🧪 테스트, ♻️ 리팩터링

#64 [BE] reservation entity 컬럼 추가 및 관련된 게스트 예약 기능 코드 수정
  src/main/java/com/beour/reservation/commons/entity/Reservation.java
  src/main/java/com/beour/reservation/commons/enums/UsagePurpose.java
  src/main/java/com/beour/reservation/guest/dto/ReservationCreateRequest.java
  src/main/java/com/beour/reservation/guest/dto/ReservationListResponseDto.java
  src/main/java/com/beour/reservation/guest/service/ReservationGuestService.java
  src/main/java/com/beour/user/dto/ChangePasswordRequestDto.java
Labels: 💡 기능, ♻️ 리팩터링, 📚코드 리뷰

#67 [BE] MyInformationController 테스트 코드를 작성한다.
  src/main/java/com/beour/user/controller/MyInfomationController.java
  src/test/java/com/beour/global/validator/implement/NullableNicknameValidatorTest.java
  src/test/java/com/beour/global/validator/implement/NullablePhoneNumberValidatorTest.java
  src/test/java/com/beour/user/controller/MyInfomationControllerTest.java
  src/test/java/com/beour/user/controller/MyInfomationControllerValidationTest.java
  src/test/java/com/beour/user/service/MyInformationServiceTest.java
Labels: 🧪 테스트, ♻️ 리팩터링
