Repository beour-team/beour-be, pull requests merged in 2025-07, with the labels that each got.

#74 [BE] CheckAvailableTimeService 테스트 코드를 작성한다.
  src/main/java/com/beour/reservation/guest/dto/CheckAvailableTimesRequestDto.java
  src/test/java/com/beour/reservation/guest/service/CheckAvailableTimeServiceTest.java
Labels: 🧪 테스트, ♻️ 리팩터링

#75 [BE] 호스트 메인화면 - 예약 정보 DTO 수정, 예약 상태 필터링 기능을 추가한다.
  src/main/java/com/beour/reservation/host/dto/HostReservationListResponseDto.java
  src/main/java/com/beour/reservation/host/service/ReservationHostService.java
Labels: 💡 기능, 📚코드 리뷰

#77 [BE] 호스트 예약캘린더 - 날짜별 예약 확인 및 필터링 기능을 구현한다.
  src/main/java/com/beour/reservation/commons/repository/ReservationRepository.java
  src/main/java/com/beour/reservation/host/controller/ReservationCalendarController.java
  src/main/java/com/beour/reservation/host/dto/CalendarReservationResponseDto.java
  src/main/java/com/beour/reservation/host/service/ReservationCalendarService.java
  src/test/java/com/beour/reservation/guest/service/ReservationGuestServiceTest.java
Labels: 💡 기능, 📚코드 리뷰

#81 [Hotfix] hotfix: ReservationRepository 코드 수정
  src/main/java/com/beour/reservation/commons/repository/ReservationRepository.java
  src/main/java/com/beour/reservation/host/controller/ReservationCalendarController.java
  src/main/java/com/beour/reservation/host/service/ReservationCalendarService.java
Labels: 🥵 핫픽스

#90 [BE] ReservationRepository 테스트 코드를 작성한다.
  src/test/java/com/beour/reservation/commons/repository/ReservationRepositoryTest.java
Labels: 🧪 테스트, ♻️ 리팩터링

#97 [BE] 최근에 등록된 리뷰를 조회하는 기능을 구현한다.
  src/main/java/com/beour/global/exception/ReviewExceptionHandler.java
  src/main/java/com/beour/global/exception/exceptionType/ReviewNotFoundException.java
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/main/java/com/beour/review/domain/repository/ReviewRepository.java
  src/main/java/com/beour/review/guest/controller/ReviewGuestController.java
  src/main/java/com/beour/review/guest/dto/RecentWrittenReviewResponseDto.java
  src/main/java/com/beour/review/guest/service/ReviewGuestService.java
Labels: 💡 기능

#98 [BE] 내공간 리스트 조회 API를 구현한다.
  src/main/java/com/beour/review/domain/repository/ReviewRepository.java
  src/main/java/com/beour/space/host/controller/SpaceController.java
  src/main/java/com/beour/space/host/dto/HostMySpaceListResponseDto.java
  src/main/java/com/beour/space/host/service/SpaceService.java
Labels: 💡 기능, 📚코드 리뷰

#105 [BE] test: ReviewRepository 테스트 코드 추가
  src/test/java/com/beour/review/domain/repository/ReviewRepositoryTest.java
Labels: 🧪 테스트, 📚코드 리뷰

#106 [BE] test: ReviewGuestControllerTest 테스트 코드 추가
  src/main/java/com/beour/global/exception/GlobalExceptionHandler.java
  src/main/java/com/beour/review/guest/service/ReviewGuestService.java
  src/test/java/com/beour/review/guest/controller/ReviewGuestControllerTest.java
Labels: 🧪 테스트, 📚코드 리뷰

#110 [#109] refactor : 공간 조회 responsebody 수정
  src/main/java/com/beour/space/guest/controller/GuestSpaceController.java
  src/main/java/com/beour/space/guest/dto/SearchSpaceResponseDto.java
  src/main/java/com/beour/space/guest/service/GuestSpaceSearchService.java
Labels: ♻️ 리팩터링

#111 [BE] test: ReviewGuestServiceTest를 작성한다
  src/main/java/com/beour/global/exception/GlobalExceptionHandler.java
  src/main/java/com/beour/global/exception/ReviewExceptionHandler.java
  src/main/java/com/beour/reservation/commons/repository/ReservationRepository.java
  src/main/java/com/beour/review/domain/entity/Review.java
  src/main/java/com/beour/review/domain/entity/ReviewImage.java
  src/main/java/com/beour/review/domain/repository/ReviewRepository.java
  src/main/java/com/beour/review/guest/service/ReviewGuestService.java
  src/test/java/com/beour/review/guest/service/ReviewGuestServiceTest.java
Labels: 🧪 테스트, ♻️ 리팩터링, 📚코드 리뷰

#112 [BE] test: ReviewCommentHostControllerTest 생성
  src/main/java/com/beour/global/exception/GlobalExceptionHandler.java
  src/main/java/com/beour/global/exception/exceptionType/ReviewCommentNotFoundException.java
  src/main/java/com/beour/review/host/service/ReviewCommentHostService.java
  src/test/java/com/beour/review/host/controller/ReviewCommentHostControllerTest.java
Labels: 🧪 테스트, ♻️ 리팩터링, 📚코드 리뷰

#114 [BE] test: ReservationCalendarControllerTest 작성
  src/test/java/com/beour/reservation/host/controller/ReservationCalendarControllerTest.java
Labels: 🧪 테스트, 📚코드 리뷰

#129 [infra] chore: cicd.yml 생성
  .github/workflows/cicd.yml
Labels: 🖥️ 인프라

#135 [infra] fix: Rename DokerFile to Dokerfile
  Dokerfile
Labels: 🖥️ 인프라, 🐞 버그

#141 [BE] Banner 등록 API 리팩터링
  .github/workflows/cicd.yml
  .gitignore
  Dockerfile
  README.md
  src/main/java/com/beour/banner/controller/BannerController.java
  src/main/java/com/beour/banner/dto/CreateBannerRequestDto.java
  src/main/java/com/beour/banner/dto/CreateBannerResponseDto.java
  src/main/java/com/beour/banner/service/BannerService.java
  src/main/java/com/beour/global/config/WebConfig.java
  src/main/java/com/beour/global/exception/FileExceptionHandler.java
  src/main/java/com/beour/global/exception/error/errorcode/ImageFileErrorCode.java
  src/main/java/com/beour/global/exception/exceptionType/ImageFileInvalidException.java
  src/main/java/com/beour/global/exception/exceptionType/ImageFileNotFoundException.java
  src/main/java/com/beour/global/file/ImageUploader.java
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/main/resources/application.yml
  src/test/java/com/beour/global/file/ImageUploaderTest.java
  src/test/java/com/beour/reservation/host/controller/ReservationHostControllerTest.java
Labels: 🧪 테스트, ♻️ 리팩터링

#146 [BE] 로그인 기능을 리팩터링하고 테스트 코드를 작성한다.
  src/main/java/com/beour/global/exception/JWTExceptionHandler.java
  src/main/java/com/beour/global/exception/error/errorcode/UserErrorCode.java
  src/main/java/com/beour/global/exception/exceptionType/LoginUserMismatchRole.java
  src/main/java/com/beour/global/exception/exceptionType/LoginUserNotFoundException.java
  src/main/java/com/beour/global/jwt/LoginFilter.java
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/main/java/com/beour/token/repository/RefreshTokenRepository.java
  src/main/java/com/beour/user/controller/LoginController.java
  src/test/java/com/beour/user/controller/LoginControllerTest.java
Labels: 🧪 테스트, ♻️ 리팩터링, 📚코드 리뷰

#147 [BE] 토큰 관련 로직들을 리팩터링 하고 테스트 코드를 추가한다.
  src/main/java/com/beour/global/exception/error/errorcode/UserErrorCode.java
  src/main/java/com/beour/global/jwt/CustomLogoutFilter.java
  src/main/java/com/beour/global/jwt/JWTFilter.java
  src/main/java/com/beour/global/jwt/LoginFilter.java
  src/main/java/com/beour/global/jwt/ManageCookie.java
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/main/java/com/beour/user/enums/TokenExpireTime.java
  src/main/java/com/beour/user/service/LoginService.java
  src/test/java/com/beour/user/controller/LoginControllerTest.java
  src/test/java/com/beour/user/service/LoginServiceTest.java
Labels: 🧪 테스트, ♻️ 리팩터링, 📚코드 리뷰

#151 [BE] 로그아웃 기능 리팩토링 및 테스트 코드를 작성한다.
  src/main/java/com/beour/global/jwt/CustomLogoutFilter.java
  src/test/java/com/beour/user/controller/LogoutControllerTest.java
Labels: 🧪 테스트, ♻️ 리팩터링, 📚코드 리뷰

#152 [BE] 사용자 정보 CRU 리팩토링 및 테스트 코드를 작성한다.
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/main/java/com/beour/user/controller/MyInfomationController.java
  src/main/java/com/beour/user/service/MyInformationService.java
  src/test/java/com/beour/user/controller/LoginControllerValidationTest.java
  src/test/java/com/beour/user/controller/MyInfomationControllerTest.java
  src/test/java/com/beour/user/controller/MyInfomationControllerValidationTest.java
Labels: ♻️ 리팩터링, 📚코드 리뷰

#154 [BE] 중복되는 내 공간 확인 GET API를 삭제한다.
  src/main/java/com/beour/space/host/controller/AvailableTimeController.java
  src/main/java/com/beour/space/host/dto/HostSpaceListResponseDto.java
  src/main/java/com/beour/space/host/service/AvailableTimeService.java
Labels: ♻️ 리팩터링, 📚코드 리뷰

#155 [BE] SPACE - website_url 컬럼 삭제 및 관련 코드 수정한다.
  src/main/java/com/beour/space/domain/entity/Description.java
  src/main/java/com/beour/space/host/dto/SpaceDetailResponseDto.java
  src/main/java/com/beour/space/host/dto/SpaceRegisterRequestDto.java
  src/main/java/com/beour/space/host/dto/SpaceUpdateRequestDto.java
  src/main/java/com/beour/space/host/service/SpaceService.java
Labels: 🛠️ 픽스, ♻️ 리팩터링

#156 Refactor/chore
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/main/java/com/beour/user/controller/LoginController.java
  src/main/java/com/beour/user/controller/SignupController.java
  src/test/java/com/beour/user/controller/LoginControllerTest.java
  src/test/java/com/beour/user/controller/LoginControllerValidationTest.java
  src/test/java/com/beour/user/controller/SignupControllerTest.java
Labels: ♻️ 리팩터링, 📚코드 리뷰

#158 [BE] KakaoMapService 리펙토링 - 하드코딩된 예외 메시지 제거 및 개선
  src/main/java/com/beour/global/exception/KakaoMapExceptionHandler.java
  src/main/java/com/beour/global/exception/error/errorcode/KakaoMapErrorCode.java
  src/main/java/com/beour/global/exception/exceptionType/KakaoMapException.java
  src/main/java/com/beour/space/host/service/KakaoMapService.java
Labels: 💡 기능, ♻️ 리팩터링, 📚코드 리뷰

#165 [infra] ImageUploaderTest 파일 업로드 테스트 수정 및 리눅스 경로 대응
  src/test/java/com/beour/global/file/ImageUploaderTest.java
Labels: 🖥️ 인프라, 🛠️ 픽스, 🧪 테스트

#167 [infra] ImageUploader 테스트 시 파일 저장 경로 누락 문제 해결
  .github/workflows/cicd.yml
Labels: 🖥️ 인프라, 🛠️ 픽스

#169 [infra] fix: cicd.yml 주석 제거
  .github/workflows/cicd.yml
Labels: 🖥️ 인프라, 🛠️ 픽스

#176 fix: CORS 허용 도메인에 HTTPS 도메인(beour.store) 추가
  src/main/java/com/beour/global/security/SecurityConfig.java
Labels: 🛠️ 픽스

#188 [BE] 게스트의 예약 API들을 리팩토링 및 테스트 코드를 수정한다.
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/main/java/com/beour/reservation/commons/repository/ReservationRepository.java
  src/main/java/com/beour/reservation/guest/controller/ReservationGuestController.java
  src/main/java/com/beour/reservation/guest/dto/CheckAvailableTimesRequestDto.java
  src/main/java/com/beour/reservation/guest/dto/ReservationCreateRequest.java
  src/main/java/com/beour/reservation/guest/dto/ReservationListPageResponseDto.java
  src/main/java/com/beour/reservation/guest/dto/ReservationListResponseDto.java
  src/main/java/com/beour/reservation/guest/service/CheckAvailableTimeService.java
  src/main/java/com/beour/reservation/guest/service/ReservationGuestService.java
  src/test/java/com/beour/reservation/commons/repository/ReservationRepositoryTest.java
  src/test/java/com/beour/reservation/guest/controller/ReservationGuestControllerTest.java
  src/test/java/com/beour/reservation/guest/controller/ReservationGuestControllerValidationTest.java
  src/test/java/com/beour/reservation/guest/service/CheckAvailableTimeServiceTest.java
  src/test/java/com/beour/reservation/guest/service/ReservationGuestServiceTest.java
Labels: 🧪 테스트, ♻️ 리팩터링, 📚코드 리뷰

#191 [BE] 공간 검색 api들을 리팩토링한다.
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/main/java/com/beour/space/domain/repository/SpaceRepository.java
  src/main/java/com/beour/space/guest/controller/GuestSpaceController.java
  src/main/java/com/beour/space/guest/dto/SearchSpacePageResponseDto.java
  src/main/java/com/beour/space/guest/dto/SearchSpaceResponseDto.java
  src/main/java/com/beour/space/guest/service/GuestSpaceSearchService.java
  src/main/java/com/beour/wishlist/repository/LikeRepository.java
Labels: ♻️ 리팩터링, 📚코드 리뷰

#201 [BE] HOST - 예약캘린더+예약 승인/거부/취소: 페이징, url 수정
  src/main/java/com/beour/reservation/commons/repository/ReservationRepository.java
  src/main/java/com/beour/reservation/host/controller/ReservationCalendarController.java
  src/main/java/com/beour/reservation/host/controller/ReservationHostController.java
  src/main/java/com/beour/reservation/host/dto/CalendarReservationPageResponseDto.java
  src/main/java/com/beour/reservation/host/dto/HostReservationListPageResponseDto.java
  src/main/java/com/beour/reservation/host/service/ReservationCalendarService.java
  src/main/java/com/beour/reservation/host/service/ReservationHostService.java
Labels: 💡 기능, ♻️ 리팩터링, 📚코드 리뷰

#203 [BE] HOST - 예약(+예약 캘린더): 페이징/url 관련 테스트 코드 수정
  src/test/java/com/beour/reservation/host/controller/ReservationCalendarControllerTest.java
  src/test/java/com/beour/reservation/host/controller/ReservationHostControllerTest.java
  src/test/java/com/beour/reservation/host/service/ReservationCalendarServiceTest.java
  src/test/java/com/beour/reservation/host/service/ReservationHostServiceTest.java
Labels: 🧪 테스트, ♻️ 리팩터링

#216 [#215] refactor: SecurityConfig url 접근 권한 매핑 수정
  src/main/java/com/beour/global/config/CorsConfig.java
  src/main/java/com/beour/global/jwt/LoginFilter.java
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/test/java/com/beour/reservation/host/controller/ReservationHostControllerTest.java
  src/test/java/com/beour/user/controller/LoginControllerTest.java
Labels: 🧪 테스트, ♻️ 리팩터링, 📚코드 리뷰

#217 Test/guestspacecontroller
  src/main/java/com/beour/space/domain/repository/SpaceRepository.java
  src/main/java/com/beour/space/guest/controller/GuestSpaceController.java
  src/main/java/com/beour/space/guest/service/GuestSpaceSearchService.java
  src/main/java/com/beour/space/guest/service/GuestSpaceService.java
  src/test/java/com/beour/reservation/guest/controller/ReservationGuestControllerTest.java
  src/test/java/com/beour/space/guest/controller/GuestSpaceControllerTest.java
Labels: 🧪 테스트, ♻️ 리팩터링, 📚코드 리뷰

#218 분리되어 있는 exceptionType 하나의 폴더로 통합
  src/main/java/com/beour/global/exception/GlobalExceptionHandler.java
  src/main/java/com/beour/global/exception/ReservationExceptionHandler.java
  src/main/java/com/beour/global/exception/SpaceExceptionHandler.java
  src/main/java/com/beour/global/exception/exceptionType/AvailableTimeNotFound.java
  src/main/java/com/beour/global/exception/exceptionType/MissMatch.java
  src/main/java/com/beour/global/exception/exceptionType/ReservationNotFound.java
  src/main/java/com/beour/reservation/guest/service/CheckAvailableTimeService.java
  src/main/java/com/beour/reservation/guest/service/ReservationGuestService.java
  src/main/java/com/beour/reservation/host/service/ReservationCalendarService.java
  src/main/java/com/beour/reservation/host/service/ReservationHostService.java
  src/main/java/com/beour/review/guest/service/ReviewGuestService.java
  src/test/java/com/beour/reservation/guest/service/CheckAvailableTimeServiceTest.java
  src/test/java/com/beour/reservation/guest/service/ReservationGuestServiceTest.java
  src/test/java/com/beour/reservation/host/service/ReservationCalendarServiceTest.java
  src/test/java/com/beour/reservation/host/service/ReservationHostServiceTest.java
  src/test/java/com/beour/review/guest/service/ReviewGuestServiceTest.java
Labels: ♻️ 리팩터링

#220 [BE] AvailableTimeControllerTest, SpaceControllerTest 작성 및 리펙토링
  src/main/java/com/beour/global/exception/GlobalExceptionHandler.java
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/main/java/com/beour/reservation/commons/repository/ReservationRepository.java
  src/main/java/com/beour/space/host/service/AvailableTimeService.java
  src/test/java/com/beour/space/host/controller/AvailableTimeControllerTest.java
  src/test/java/com/beour/space/host/controller/SpaceControllerTest.java
Labels: 🧪 테스트, ♻️ 리팩터링, 📚코드 리뷰

#228 [BE] access token, refresh token 만료 에러 코드를 수정한다.
  src/main/java/com/beour/global/exception/JWTExceptionHandler.java
  src/main/java/com/beour/global/exception/error/errorcode/UserErrorCode.java
Labels: ♻️ 리팩터링

#232 refactor: spacecategory에 etc 항목 추가
  src/main/java/com/beour/space/domain/enums/SpaceCategory.java
Labels: ♻️ 리팩터링

#231 fix: test코드 수정
  src/main/java/com/beour/space/domain/enums/SpaceCategory.java
  src/test/java/com/beour/user/controller/LoginControllerTest.java
Labels: 🛠️ 픽스
