Repository beour-team/beour-be, pull requests merged in 2025-05, with the labels that each got.

#8 [BE] 회원가입, 로그인 기능을 구현한다.
  build.gradle
  src/main/java/com/beour/BeourApplication.java
  src/main/java/com/beour/global/config/CorsMvcConfig.java
  src/main/java/com/beour/global/entity/BaseTimeEntity.java
  src/main/java/com/beour/global/exception/ErrorResponse.java
  src/main/java/com/beour/global/exception/GlobalExceptionHandler.java
  src/main/java/com/beour/global/exception/UserExceptionHandler.java
  src/main/java/com/beour/global/exception/exceptionType/DuplicateUserInfoException.java
  src/main/java/com/beour/global/exception/exceptionType/InvalidCredentialsException.java
  src/main/java/com/beour/global/exception/exceptionType/UserException.java
  src/main/java/com/beour/global/exception/exceptionType/UserNotFoundException.java
  src/main/java/com/beour/global/jwt/JWTFilter.java
  src/main/java/com/beour/global/jwt/JWTUtil.java
  src/main/java/com/beour/global/jwt/LoginFilter.java
  src/main/java/com/beour/global/response/ErrorResponse.java
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/main/java/com/beour/user/controller/LoginController.java
  src/main/java/com/beour/user/controller/SignupController.java
  src/main/java/com/beour/user/dto/CheckDuplicateLoginIdDto.java
  src/main/java/com/beour/user/dto/CheckDuplicateNickNameDto.java
  src/main/java/com/beour/user/dto/CustomUserDetails.java
  src/main/java/com/beour/user/dto/FindLoginIdRequestDto.java
  src/main/java/com/beour/user/dto/FindLoginIdResponseDto.java
  src/main/java/com/beour/user/dto/LoginDto.java
  src/main/java/com/beour/user/dto/ResetPasswordRequestDto.java
  src/main/java/com/beour/user/dto/ResetPasswordResponseDto.java
  src/main/java/com/beour/user/dto/SignupDto.java
  src/main/java/com/beour/user/entity/User.java
  src/main/java/com/beour/user/repository/UserRepository.java
  src/main/java/com/beour/user/service/CustomUserDetailsService.java
  src/main/java/com/beour/user/service/LoginService.java
  src/main/java/com/beour/user/service/SignupService.java
  src/main/resources/application.yml
Labels: 코드 리뷰

#9 [BE] 호스트 공간 정보 등록 기능을 구현한다.
  build.gradle
  src/main/java/com/beour/global/entity/BaseTimeEntity.java
  src/main/java/com/beour/space/host/controller/SpaceController.java
  src/main/java/com/beour/space/host/dto/SpaceRegisterRequestDto.java
  src/main/java/com/beour/space/host/entity/AvailableTime.java
  src/main/java/com/beour/space/host/entity/Description.java
  src/main/java/com/beour/space/host/entity/Space.java
  src/main/java/com/beour/space/host/entity/SpaceImage.java
  src/main/java/com/beour/space/host/entity/Tag.java
  src/main/java/com/beour/space/host/enums/SpaceCategory.java
  src/main/java/com/beour/space/host/enums/UseCategory.java
  src/main/java/com/beour/space/host/repository/AvailableTimeRepository.java
  src/main/java/com/beour/space/host/repository/DescriptionRepository.java
  src/main/java/com/beour/space/host/repository/SpaceImageRepository.java
  src/main/java/com/beour/space/host/repository/SpaceRepository.java
  src/main/java/com/beour/space/host/repository/TagRepository.java
  src/main/java/com/beour/space/host/service/KakaoMapService.java
  src/main/java/com/beour/space/host/service/SpaceService.java
  src/main/java/com/beour/space/host/service/UserService.java
  src/main/java/com/beour/user/entity/User.java
  src/main/java/com/beour/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: 코드 리뷰

#12 [BE] 호스트 공간 정보 삭제 기능을 구현한다.
  src/main/java/com/beour/space/host/controller/SpaceController.java
  src/main/java/com/beour/space/host/entity/Space.java
  src/main/java/com/beour/space/host/service/SpaceService.java
Labels: 코드 리뷰

#10 [BE] 호스트 공간 정보 수정 기능을 구현한다.
  src/main/java/com/beour/space/host/controller/SpaceController.java
  src/main/java/com/beour/space/host/dto/SpaceUpdateRequestDto.java
  src/main/java/com/beour/space/host/entity/AvailableTime.java
  src/main/java/com/beour/space/host/entity/Description.java
  src/main/java/com/beour/space/host/entity/Space.java
  src/main/java/com/beour/space/host/entity/SpaceImage.java
  src/main/java/com/beour/space/host/entity/Tag.java
  src/main/java/com/beour/space/host/repository/AvailableTimeRepository.java
  src/main/java/com/beour/space/host/repository/SpaceImageRepository.java
  src/main/java/com/beour/space/host/repository/TagRepository.java
  src/main/java/com/beour/space/host/service/KakaoMapService.java
  src/main/java/com/beour/space/host/service/SpaceService.java
Labels: 📚코드 리뷰

#15 Move: space-host에 entity, repo를 space-domain으로 옮김
  src/main/java/com/beour/space/domain/entity/AvailableTime.java
  src/main/java/com/beour/space/domain/entity/Description.java
  src/main/java/com/beour/space/domain/entity/Space.java
  src/main/java/com/beour/space/domain/entity/SpaceImage.java
  src/main/java/com/beour/space/domain/entity/Tag.java
  src/main/java/com/beour/space/domain/repository/AvailableTimeRepository.java
  src/main/java/com/beour/space/domain/repository/DescriptionRepository.java
  src/main/java/com/beour/space/domain/repository/SpaceImageRepository.java
  src/main/java/com/beour/space/domain/repository/SpaceRepository.java
  src/main/java/com/beour/space/domain/repository/TagRepository.java
  src/main/java/com/beour/space/host/service/SpaceService.java
Labels: ♻️ 리팩터링

#17 [BE] 가까운 공간 리스트 조회 구현
  src/main/java/com/beour/space/domain/repository/SpaceRepository.java
  src/main/java/com/beour/space/guest/controller/GuestSpaceController.java
  src/main/java/com/beour/space/guest/dto/NearbySpaceResponse.java
  src/main/java/com/beour/space/guest/service/GuestSpaceService.java
  src/main/java/com/beour/wishlist/entity/Like.java
  src/main/java/com/beour/wishlist/repository/LikeRepository.java
Labels: 💡 기능, 📚코드 리뷰

#21 [#6] refactor: 로그인 로직 수정
  src/main/java/com/beour/global/jwt/LoginFilter.java
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/main/java/com/beour/user/dto/LoginDto.java
  src/main/java/com/beour/user/service/CustomUserDetailsService.java
Labels: ♻️ 리팩터링, 📚코드 리뷰

#23 [BE] 검색 기능을 구현한다.
  build.gradle
  src/main/java/com/beour/global/exception/GlobalExceptionHandler.java
  src/main/java/com/beour/global/exception/exceptionType/InputInvalidFormatException.java
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/main/java/com/beour/space/domain/repository/SpaceRepository.java
  src/main/java/com/beour/space/guest/controller/GuestSpaceController.java
  src/main/java/com/beour/space/guest/dto/FilteringSearchRequestDto.java
  src/main/java/com/beour/space/guest/dto/SearchSpaceResponseDto.java
  src/main/java/com/beour/space/guest/service/GuestSpaceSearchService.java
Labels: 💡 기능, 📚코드 리뷰

#28 [BE] 공간 찜, 삭제, 조회를 구현한다.
  src/main/java/com/beour/global/exception/WishListExceptionHandler.java
  src/main/java/com/beour/global/exception/exceptionType/DuplicateLikesException.java
  src/main/java/com/beour/global/exception/exceptionType/DuplicateUserInfoException.java
  src/main/java/com/beour/global/exception/exceptionType/LikesNotFoundException.java
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/main/java/com/beour/space/guest/dto/SpaceListSpaceResponseDto.java
  src/main/java/com/beour/wishlist/controller/WishlistController.java
  src/main/java/com/beour/wishlist/dto/MakeWishlistResponseDto.java
  src/main/java/com/beour/wishlist/entity/Like.java
  src/main/java/com/beour/wishlist/repository/LikeRepository.java
  src/main/java/com/beour/wishlist/service/WishlistService.java
Labels: 💡 기능, 📚코드 리뷰
