Repository beour-team/beour-be, pull requests merged in 2025-08, with the labels that each got.

#240 [배포] 게스트의 취소된 예약 목록 조회, 예약 상세 조회 api 추가
  src/main/java/com/beour/banner/controller/BannerController.java
  src/main/java/com/beour/global/security/SecurityConfig.java
  src/main/java/com/beour/reservation/commons/repository/ReservationRepository.java
  src/main/java/com/beour/reservation/guest/controller/ReservationGuestController.java
  src/main/java/com/beour/reservation/guest/dto/DetailReservationResponseDto.java
  src/main/java/com/beour/reservation/guest/service/ReservationGuestService.java
  src/test/java/com/beour/reservation/guest/controller/ReservationGuestControllerTest.java
Labels: 💡 기능, 🧪 테스트

#251 [BE] Category 한글 라벨 매핑 추가 및 응답Dto에 한글 라벨 리턴하도록 수정
  src/main/java/com/beour/reservation/commons/enums/ReservationStatus.java
  src/main/java/com/beour/reservation/guest/dto/DetailReservationResponseDto.java
  src/main/java/com/beour/reservation/guest/dto/ReservationListResponseDto.java
  src/main/java/com/beour/reservation/host/dto/CalendarReservationResponseDto.java
  src/main/java/com/beour/reservation/host/dto/HostReservationListResponseDto.java
  src/main/java/com/beour/review/guest/dto/ReviewForReservationResponseDto.java
  src/main/java/com/beour/review/guest/dto/ReviewableReservationResponseDto.java
  src/main/java/com/beour/space/domain/enums/SpaceCategory.java
  src/main/java/com/beour/space/domain/enums/UseCategory.java
  src/main/java/com/beour/space/host/dto/SpaceDetailResponseDto.java
  src/main/java/com/beour/space/host/service/SpaceService.java
  src/test/java/com/beour/reservation/guest/service/ReservationGuestServiceTest.java
  src/test/java/com/beour/reservation/host/service/ReservationCalendarServiceTest.java
  src/test/java/com/beour/reservation/host/service/ReservationHostServiceTest.java
  src/test/java/com/beour/review/guest/service/ReviewGuestServiceTest.java
Labels: 💡 기능, ♻️ 리팩터링

#256 [BE] ReviewForReservationResponseDto에 썸네일 필드 추가
  src/main/java/com/beour/review/guest/dto/ReviewForReservationResponseDto.java
Labels: ♻️ 리팩터링

#259 [BE] fix: Reservation관련 Test코드 DateTimeException
  .github/workflows/cicd.yml
  src/test/java/com/beour/reservation/commons/repository/ReservationRepositoryTest.java
  src/test/java/com/beour/reservation/guest/service/ReservationGuestServiceTest.java
  src/test/java/com/beour/reservation/host/service/ReservationHostServiceTest.java
Labels: 🛠️ 픽스, 🐞 버그

#265 [BE] fix: 호스트 작성한 리뷰 조회 API에 reviewCommentId 필드 추가
  src/main/java/com/beour/review/host/dto/ReviewCommentResponseDto.java
Labels: 🛠️ 픽스
